using System.Collections.Generic;
using LearnGame26.Pages;

namespace LearnGame26.Pages
{
    public static class QuestionList1
    {
        public static List<Question> GetQuestions()
        {
            return new List<Question>
            {
                 new Question { Text = "Care este molecula purtătoare de informație genetică în celule?", VarA = "Proteina", VarB = "ARN", VarC = "ADN", RaspunsCorect = 3 },
new Question { Text = "Ce organ din corpul uman este responsabil pentru pomparea sângelui?", VarA = "Ficatul", VarB = "Inima", VarC = "Plămânii", RaspunsCorect = 2 },
    new Question { Text = "Care este procesul prin care plantele produc oxigen?", VarA = "Fotosinteza", VarB = "Respirația", VarC = "Transpirația", RaspunsCorect = 1 },
new Question { Text = "Cum se numește partea colorată a ochiului uman?", VarA = "Corneea", VarB = "Pupila", VarC = "Irisul", RaspunsCorect = 3 },
new Question { Text = "Care este cel mai mare os din corpul uman?", VarA = "Tibia", VarB = "Femurul", VarC = "Humerusul", RaspunsCorect = 2 },
new Question { Text = "Care este organitul celular responsabil pentru producerea energiei?", VarA = "Ribozomul", VarB = "Mitocondria", VarC = "Nucleul", RaspunsCorect = 2 },
new Question { Text = "Cum se numește procesul de diviziune celulară în celulele somatice?", VarA = "Meioza", VarB = "Mitoza", VarC = "Citokineza", RaspunsCorect = 2 },
new Question { Text = "Care este elementul principal al hemoglobinei din sânge?", VarA = "Fierul", VarB = "Calciul", VarC = "Sodiul", RaspunsCorect = 1 },
new Question { Text = "Care grupă de sânge este cunoscută ca fiind donator universal?", VarA = "AB+", VarB = "0", VarC = "B+", RaspunsCorect = 2 },
new Question { Text = "Cum se numește membrana care acoperă și protejează creierul?", VarA = "Peritoneu", VarB = "Meninge", VarC = "Pleura", RaspunsCorect = 2 },

new Question { Text = "Ce înseamnă 'Manus manum lavat'?", VarA = "o mână o spală pe alta", VarB = "să se facă lumină", VarC = "avem papă", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă 'Dura lex, sed lex'?", VarA = "Legea trebuie respectată", VarB = "vocea poporului, vocea zeilor", VarC = "Legea e dură, dar e lege", RaspunsCorect = 3 },
new Question { Text = "Ce înseamnă 'Nosce te ipsum'?", VarA = "Trăiește clipa", VarB = "cunoaște-te pe tine însuți", VarC = "ferește-te de câini", RaspunsCorect = 2 },
new Question { Text = "Ce înseamnă 'Vox populi, vox dei'?", VarA = "Am venit, am văzut, am învins", VarB = "vocea poporului, vocea zeilor", VarC = "Am sperat, am câștigat", RaspunsCorect = 2 },
new Question { Text = "Ce înseamnă 'cave canem'?", VarA = "Zarurile au fost aruncate", VarB = "câinii latră", VarC = "ferește-te de câini", RaspunsCorect = 3 },
new Question { Text = "Ce înseamnă 'Suum cuique'?", VarA = "Fiecare își primește partea", VarB = "Nimeni nu este perfect", VarC = "Totul trece", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă 'Memento mori'?", VarA = "Amintește-ți că vei muri", VarB = "Trăiește pentru moment", VarC = "Învață din trecut", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă 'In vino veritas'?", VarA = "În vin este adevărul", VarB = "Bucură-te de viață", VarC = "Vinul este sănătos", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă 'Fortuna favet fortibus'?", VarA = "Norocul favorizează pe cei curajoși", VarB = "Norocul vine la cei care așteaptă", VarC = "Norocul este o iluzie", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă 'Cogito, ergo sum'?", VarA = "Gândesc, deci exist", VarB = "Trăiesc, deci gândesc", VarC = "Sunt, deci gândesc", RaspunsCorect = 1 },

new Question { Text = "Cum se numește partea exterioară care alcătuiește o celulă?", VarA = "citoplasmă", VarB = "nucleu", VarC = "membrana", RaspunsCorect = 3 },
new Question { Text = "Care din următoarele transportă cea mai mică cantitate de sânge?", VarA = "capilarele", VarB = "arterele", VarC = "venele", RaspunsCorect = 1 },
new Question { Text = "Care organ se ocupă cu producerea de zaharuri care hrănesc planta?", VarA = "rădăcina", VarB = "florile", VarC = "frunzele", RaspunsCorect = 3 },
new Question { Text = "Ce tip de celule sunt responsabile pentru combaterea infecțiilor?", VarA = "Celule roșii", VarB = "Celule albe", VarC = "Neuronii", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai mare organ al corpului uman?", VarA = "Ficatul", VarB = "Pielea", VarC = "intestinul gros", RaspunsCorect = 2 },
new Question { Text = "Ce formează o multitudine de țesuturi?", VarA = "organismul", VarB = "organul", VarC = "celula", RaspunsCorect = 2 },
new Question { Text = "Ce organ vizează Alanina aminotransferază (ALT)?", VarA = "inima", VarB = "ficatul", VarC = "pancreasul", RaspunsCorect = 2 },
new Question { Text = "Cum se numește în termeni științifici cerul gurii?", VarA = "bolta palatină", VarB = "bolta maxilară", VarC = "bolta mandibulară", RaspunsCorect = 1 },
new Question { Text = "Ce hormon este responsabil pentru reglarea glicemiei în sânge?", VarA = "Adrenalină", VarB = "Insulină", VarC = "Testosteron", RaspunsCorect = 2 },
new Question { Text = "Care este denumirea științifică pentru osul coapsei?", VarA = "Tibia", VarB = "Femur", VarC = "Peroneu", RaspunsCorect = 2 },
//30


new Question { Text = "Care este capitala Japoniei?", VarA = "Kyoto", VarB = "Osaka", VarC = "Tokyo", RaspunsCorect = 3 },
new Question { Text = "Câte zile are un an bisect?", VarA = "365", VarB = "366", VarC = "364", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai înalt munte din lume?", VarA = "Mont Blanc", VarB = "Mount Everest", VarC = "K2", RaspunsCorect = 2 },
new Question { Text = "Ce element chimic are simbolul Hg?", VarA = "Hidrogen", VarB = "Heliu", VarC = "Mercur", RaspunsCorect = 3 },
new Question { Text = "Cine a pictat tabloul Mona Lisa?", VarA = "Leonardo da Vinci", VarB = "Michelangelo", VarC = "Pablo Picasso", RaspunsCorect = 1 },
new Question { Text = "Care este cea mai mare planetă din sistemul solar?", VarA = "Marte", VarB = "Jupiter", VarC = "Saturn", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai mare stat din punct de vedere al suprafeței?", VarA = "SUA", VarB = "Rusia", VarC = "China", RaspunsCorect = 2 },
new Question { Text = "Care din următoarele state se află înconjurat de o singură altă țară?", VarA = "Vatican", VarB = "Elveția", VarC = "Estonia", RaspunsCorect = 1 },
new Question { Text = "Cine a compus Simfonia a șaptea?", VarA = "Johann Sebastian Bach", VarB = "Ludwig van Beethoven", VarC = "Wolfgang Amadeus Mozart", RaspunsCorect = 2 },
new Question { Text = "Care este capitala Norvegiei?", VarA = "Stockholm", VarB = "Talinn", VarC = "Oslo", RaspunsCorect = 3 },

new Question { Text = "Cum se traduce în română expresia latină 'Carpe diem'?", VarA = "Trăiește clipa", VarB = "Grăbește-te încet", VarC = "Știința este putere", RaspunsCorect = 1 },
new Question { Text = "Care este traducerea expresiei latine 'Alea iacta est'?", VarA = "Lupta continuă", VarB = "Zarurile au fost aruncate", VarC = "Cunoaște-te pe tine însuți", RaspunsCorect = 2 },
new Question { Text = "Cum se traduce în română expresia latină 'Veni, vidi, vici'?", VarA = "Am venit, am văzut, am cucerit", VarB = "Divide și stăpânește", VarC = "Puterea înseamnă cunoaștere", RaspunsCorect = 1 },
new Question { Text = "Care este traducerea expresiei latine 'In vino veritas'?", VarA = "Adevărul este în vin", VarB = "Cunoașterea este putere", VarC = "Mânia este scurtă nebunie", RaspunsCorect = 1 },
new Question { Text = "Cum se traduce în română expresia latină 'Cogito, ergo sum'?", VarA = "Speranța moare ultima", VarB = "cuget, deci exist", VarC = "Cunoașterea vine din experiență", RaspunsCorect = 2 },

new Question { Text = "What is the past tense of the verb 'go'?", VarA = "goed", VarB = "went", VarC = "gone", RaspunsCorect = 2 },
new Question { Text = "Which word is a synonym for 'happy'?", VarA = "sad", VarB = "joyful", VarC = "angry", RaspunsCorect = 2 },
new Question { Text = "What is the plural form of 'child'?", VarA = "childs", VarB = "childrens", VarC = "children", RaspunsCorect = 3 },
new Question { Text = "Which article is used before a word starting with m and is plural?", VarA = "a", VarB = "an", VarC = "the", RaspunsCorect = 3 },
new Question { Text = "What is the comparative form of 'good'?", VarA = "better", VarB = "gooder", VarC = "best", RaspunsCorect = 1 },
new Question { Text = "Which of the following is a conjunction?", VarA = "quickly", VarB = "and", VarC = "he", RaspunsCorect = 2 },
new Question { Text = "What is the opposite of 'cold'?", VarA = "windy", VarB = "freezing", VarC = "hot", RaspunsCorect = 3 },
new Question { Text = "Which word is spelled correctly?", VarA = "recieve", VarB = "receive", VarC = "receeve", RaspunsCorect = 2 },
new Question { Text = "Which sentence is in the future tense?", VarA = "I will go to the store.", VarB = "I am going to the store.", VarC = "I went to the store.", RaspunsCorect = 1 },
new Question { Text = "Which pronoun would replace 'Mary and I'?", VarA = "They", VarB = "We", VarC = "Us", RaspunsCorect = 2 },

new Question { Text = "Cine este autorul romanului \"Mândrie și prejudecată\"?", VarA = "Jane Austen", VarB = "Charlotte Brontë", VarC = "Stendhal", RaspunsCorect = 1 },
new Question { Text = "Care este titlul celei mai cunoscute opere a lui William Shakespeare?", VarA = "Hamlet", VarB = "Romeo și Julieta", VarC = "Macbeth", RaspunsCorect = 2 },
new Question { Text = "În care carte a lui Jules Verne se găsește aventura submarină a Nautilusului?", VarA = "Ocolul Pământului în 80 de zile", VarB = "Cinci săptămâni în balon", VarC = "20.000 de leghe sub mări", RaspunsCorect = 3 },
new Question { Text = "Cine este autorul poeziei \"Luceafărul\"?", VarA = "Mihai Eminescu", VarB = "George Coșbuc", VarC = "Lucian Blaga", RaspunsCorect = 1 },
new Question { Text = "Care este numele personajului principal din romanul \"Don Quijote\" al lui Miguel de Cervantes?", VarA = "Don Quijote", VarB = "Sancho Panza", VarC = "Rocinante", RaspunsCorect = 1 },
new Question { Text = "Cine a scris romanul \"Război și pace\"?", VarA = "Fyodor Dostoevsky", VarB = "Leo Tolstoy", VarC = "Anton Chekhov", RaspunsCorect = 2 },
new Question { Text = "Ce scriitor francez a scris opera Mizerabilii?", VarA = "Gustave Flaubert", VarB = "Alexandre Dumas", VarC = "Victor Hugo", RaspunsCorect = 3 },
new Question { Text = "În care dintre aceste opere ale lui Mark Twain apare personajul Huck Finn?", VarA = "Aventurile lui Tom Sawyer", VarB = "Prinț și cerșetor", VarC = "Aventurile lui Huckleberry Finn", RaspunsCorect = 3 },
new Question { Text = "Cine este autorul romanului \"Crimă și pedeapsă\"?", VarA = "Fyodor Dostoevsky", VarB = "Leo Tolstoy", VarC = "Ivan Turgenev", RaspunsCorect = 1 },
new Question { Text = "În ce operă literară găsim personajul Jay Gatsby?", VarA = "Frumoasa și Bestia", VarB = "Marele Gatsby", VarC = "Război și pace", RaspunsCorect = 2 },

new Question { Text = "Cine a fost primul împărat al Romei?", VarA = "Cezar Augustus", VarB = "Julius Caesar", VarC = "Nero", RaspunsCorect = 1 },
new Question { Text = "În ce an a început al Doilea Război Mondial?", VarA = "1937", VarB = "1939", VarC = "1940", RaspunsCorect = 2 },
new Question { Text = "Care a fost primul președinte al Statelor Unite?", VarA = "Thomas Jefferson", VarB = "Abraham Lincoln", VarC = "George Washington", RaspunsCorect = 3 },
new Question { Text = "Cine a fost conducătorul armatei macedonene care a cucerit mare parte din lumea cunoscută?", VarA = "Alexandru cel Mare", VarB = "Darius I", VarC = "Xerxes", RaspunsCorect = 1 },
new Question { Text = "În ce an a căzut Constantinopolul sub stăpânirea otomanilor?", VarA = "1453", VarB = "1492", VarC = "1520", RaspunsCorect = 1 },
new Question { Text = "Care civilizație antică a construit piramidele din Giza?", VarA = "Maya", VarB = "Egipteană", VarC = "Mesopotamiană", RaspunsCorect = 2 },
new Question { Text = "Cine a descoperit America în 1492?", VarA = "Fernando Magellan", VarB = "Cristofor Columb", VarC = "Vasco da Gama", RaspunsCorect = 2 },
new Question { Text = "În ce an a fost semnată Declarația de Independență a Statelor Unite?", VarA = "1667", VarB = "1783", VarC = "1776", RaspunsCorect = 3 },
new Question { Text = "Care regină britanică a avut cea mai lungă domnie înainte de regina Elisabeta a II-a?", VarA = "Regina Victoria", VarB = "Regina Mary", VarC = "Regina Anne", RaspunsCorect = 1 },
new Question { Text = "Cine a fost liderul revoluționar al independenței Indiei?", VarA = "Mahatma Gandhi", VarB = "Jawaharlal Nehru", VarC = "Subhas Chandra Bose", RaspunsCorect = 1 },

new Question { Text = "What is the plural form of 'mouse'?", VarA = "mouses", VarB = "mices", VarC = "mice", RaspunsCorect = 3 },
new Question { Text = "Which of the following is an antonym for 'weak'?", VarA = "tall", VarB = "Joyful", VarC = "strong", RaspunsCorect = 3 },
new Question { Text = "What is the past perfect of 'see'?", VarA = "sea", VarB = "see", VarC = "seen", RaspunsCorect = 3 },
new Question { Text = "Which of the following words is an adjective in positive form?", VarA = "Quickly", VarB = "Quick", VarC = "Quicker", RaspunsCorect = 2 },
new Question { Text = "What is the translation of the word 'yard'?", VarA = "grădină", VarB = "curte", VarC = "proprietate", RaspunsCorect = 2 },
new Question { Text = "Which word is a short adjective?", VarA = "sad", VarB = "beautiful", VarC = "good", RaspunsCorect = 1 },
new Question { Text = "What is the superlative form of 'good'?", VarA = "Best", VarB = "Better", VarC = "Gooder", RaspunsCorect = 1 },
new Question { Text = "Which sentence is correct?", VarA = "She don't like apples.", VarB = "She doesn't likes apples.", VarC = "She doesn't like apples.", RaspunsCorect = 3 },
new Question { Text = "What is the antonym of 'hot'?", VarA = "Warm", VarB = "Cold", VarC = "Boiling", RaspunsCorect = 2 },
new Question { Text = "What is the correct form of the verb in the sentence: 'He ___ to the store every day'?", VarA = "Go", VarB = "Goes", VarC = "Going", RaspunsCorect = 2 },
//85

new Question { Text = "Ce înseamnă CPU în terminologia calculatoarelor?", VarA = "Unitatea Centrală de Procesare", VarB = "Unitatea Personală de Calcul", VarC = "Unitatea Centrală Periferică", RaspunsCorect = 1 },
new Question { Text = "Care este funcția principală a RAM în calculator?", VarA = "Pentru a stoca fișiere permanent", VarB = "Pentru a efectua calcule", VarC = "Pentru a stoca date temporar", RaspunsCorect = 3 },
new Question { Text = "Ce limbaj de programare este cunoscut pentru utilizarea sa în dezvoltarea web și este adesea asociat cu HTML și CSS?", VarA = "Python", VarB = "JavaScript", VarC = "C++", RaspunsCorect = 2 },
new Question { Text = "Care este numele protocolului de rețea utilizat pentru transferul fișierelor de la un gazdă la alta?", VarA = "FTP", VarB = "HTTP", VarC = "SMTP", RaspunsCorect = 1 },
new Question { Text = "În ce an a fost lansat primul iPhone?", VarA = "2005", VarB = "2007", VarC = "2009", RaspunsCorect = 2 },
new Question { Text = "Ce tehnologie este folosită pentru a face posibile apelurile telefonice prin internet?", VarA = "VoIP", VarB = "VPN", VarC = "VoLTE", RaspunsCorect = 1 },
new Question { Text = "Ce companie a dezvoltat sistemul de operare Android?", VarA = "Apple", VarB = "Microsoft", VarC = "Google", RaspunsCorect = 3 },
new Question { Text = "Ce înseamnă HTML?", VarA = "HyperText Markup Language", VarB = "Hyperlink Text Management Language", VarC = "HyperTool Multi Language", RaspunsCorect = 1 },
new Question { Text = "Care dispozitiv este utilizat în principal ca memorie principală într-un calculator?", VarA = "Hard Disk", VarB = "RAM", VarC = "SSD", RaspunsCorect = 2 },
new Question { Text = "Care este funcția principală a unui firewall într-o rețea de calculatoare?", VarA = "Pentru a stoca date", VarB = "Pentru a bloca accesul neautorizat", VarC = "Pentru a accelera rețeaua", RaspunsCorect = 2 },

new Question { Text = "Ce specie a genului epic este opera Moara cu noroc scrisă de Ioan Slavici?", VarA = "roman", VarB = "nuvelă", VarC = "povestire în ramă", RaspunsCorect = 2 },
new Question { Text = "Care este numele real al lui Ion Barbu?", VarA = "Ion Barbilian", VarB = "Dan Barbu", VarC = "Dan Barbilian", RaspunsCorect = 3 },
new Question { Text = "Cine este autorul comediei 'O scrisoare pierdută'?", VarA = "Ion Luca Caragiale", VarB = "Ion Creangă", VarC = "Liviu Rebreanu", RaspunsCorect = 1 },
new Question { Text = "Care este titlul romanului scris de Fyodor Dostoevsky în care apare personajul Raskolnikov?", VarA = "Crimă și pedeapsă", VarB = "Frații Karamazov", VarC = "Idiotul", RaspunsCorect = 1 },
new Question { Text = "Cine a scris romanul 'Anna Karenina'?", VarA = "Leo Tolstoy", VarB = "Fyodor Dostoevsky", VarC = "Anton Chekhov", RaspunsCorect = 1 },
new Question { Text = "Cum îl cheamă pe învățătorul din romanul Ion scris de Liviu Rebreanu?", VarA = "Belciug", VarB = "Avrum", VarC = "Herdelea", RaspunsCorect = 3 },
new Question { Text = "Ce operă a reprezentat sursa de inspirație pentru romanul Enigma Otiliei scrisă de George Călinescu", VarA = "Moș Goriot", VarB = "Les Misérables", VarC = "Roșu și negru", RaspunsCorect = 1 },
new Question { Text = "Cum se numește romanul ce se desfășoară în perioada Războiului de secesiune din America?", VarA = "Mânăstirea din Parma", VarB = "Pasărea Phoenix", VarC = "Pe aripile vântului", RaspunsCorect = 3 },
new Question { Text = "Cine este autorul romanului 'Război și pace'?", VarA = "Leo Tolstoy", VarB = "Fyodor Dostoevsky", VarC = "Anton Chekhov", RaspunsCorect = 1 },
new Question { Text = "Cine a scris tragedia antică 'Hamlet'?", VarA = "William Shakespeare", VarB = "Johann Wolfgang von Goethe", VarC = "Christopher Marlowe", RaspunsCorect = 1 },

new Question { Text = "În ce an a avut loc Marea Unire a Principatelor Române?", VarA = "1859", VarB = "1877", VarC = "1918", RaspunsCorect = 3 },
new Question { Text = "Cine a fost primul președinte al României după căderea comunismului?", VarA = "Ion Iliescu", VarB = "Emil Constantinescu", VarC = "Adrian Năstase", RaspunsCorect = 1 },
new Question { Text = "În ce an a avut loc Revoluția Franceză?", VarA = "1789", VarB = "1830", VarC = "1848", RaspunsCorect = 1 },
new Question { Text = "Cine a fost primul conducător al comunismului din Rusia?", VarA = "Stalin", VarB = "Lenin", VarC = "Hrâsciov", RaspunsCorect = 2 },
new Question { Text = "Cine a fost primul om care a ajuns pe Lună?", VarA = "Buzz Aldrin", VarB = "Neil Armstrong", VarC = "Michael Collins", RaspunsCorect = 2 },
new Question { Text = "Când a avut loc Bătălia de la Waterloo?", VarA = "1812", VarB = "1815", VarC = "1805", RaspunsCorect = 2 },
new Question { Text = "Care este numele celei mai faimoase dinastii chineze?", VarA = "Han", VarB = "Ming", VarC = "Qing", RaspunsCorect = 1 },
new Question { Text = "Cine a fost primul om care a navigat în jurul Pământului?", VarA = "Christopher Columb", VarB = "Fernando Magellan", VarC = "James Cook", RaspunsCorect = 2 },
new Question { Text = "În ce an a avut loc debarcarea aliaților în Normandia (Ziua D)?", VarA = "1918", VarB = "1944", VarC = "1945", RaspunsCorect = 2 },
new Question { Text = "Între ce ani s-a desfășurat Primul Război Mondial?", VarA = "1916-1918", VarB = "1916-1920", VarC = "1914-1918", RaspunsCorect = 3 },

new Question { Text = "Care buton trebuie apăsat pentru repornirea unui dispozitiv electronic?", VarA = "resetare", VarB = "restartare", VarC = "oprire", RaspunsCorect = 2 },
new Question { Text = "Care este limbajul de programare care se prescurtează C#?", VarA = "C", VarB = "C sharp", VarC = "C++", RaspunsCorect = 2 },
new Question { Text = "Ce companie a dezvoltat sistemul de operare Windows?", VarA = "Apple", VarB = "Microsoft", VarC = "Google", RaspunsCorect =2  },
new Question { Text = "Ce tehnologie este utilizată pentru a cripta comunicațiile pe internet?", VarA = "HTML", VarB = "CSS", VarC = "SSL/TLS", RaspunsCorect = 3 },
new Question { Text = "Ce componentă a unui computer este responsabilă pentru redarea graficelor?", VarA = "CPU", VarB = "RAM", VarC = "GPU", RaspunsCorect = 3 },
new Question { Text = "Ce este un SSD?", VarA = "Solid State Drive", VarB = "Simple Storage Device", VarC = "Standard State Drive", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă URL?", VarA = "Uniform Resource Locator", VarB = "Universal Resource Locator", VarC = "Unified Resource Locator", RaspunsCorect = 1 },
new Question { Text = "Ce companie a dezvoltat primul microprocesor?", VarA = "Intel", VarB = "AMD", VarC = "Nvidia", RaspunsCorect = 1 },
new Question { Text = "Care este extensia fișierelor executabile în Windows?", VarA = ".exe", VarB = ".xml", VarC = ".cmd", RaspunsCorect = 1 },
new Question { Text = "Ce este Git?", VarA = "Un sistem de control al versiunilor", VarB = "Un limbaj de programare", VarC = "O aplicație de editare foto", RaspunsCorect = 1 },

new Question { Text = "Care sunt unitățile structurale de bază ale organismului?", VarA = "Țesuturi", VarB = "Celule", VarC = "Organe", RaspunsCorect = 2 },
new Question { Text = "Ce tip de celule sunt responsabile pentru transportul oxigenului?", VarA = "Celule albe", VarB = "Celule roșii", VarC = "Plachete sanguine", RaspunsCorect = 2 },
new Question { Text = "Ce molecule sunt principalul produs al fotosintezei?", VarA = "Amoniac", VarB = "Dioxid de carbon", VarC = "Glucide", RaspunsCorect = 3 },
new Question { Text = "Cum se numește procesul prin care plantele își produc propria hrană?", VarA = "Respirație", VarB = "Fotosinteză", VarC = "Fermentație", RaspunsCorect = 2 },
new Question { Text = "Care este funcția principală a sistemului circulator?", VarA = "Transportul nutrienților și oxigenului", VarB = "Digestia alimentelor", VarC = "Reproducția", RaspunsCorect = 1 },
new Question { Text = "Ce tip de ADN se găsește în mitocondrii?", VarA = "ADN nuclear", VarB = "ADN mitocondrial", VarC = "ADN plasmidic", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai mic tip de celule din sângele uman?", VarA = "Celule roșii", VarB = "Celule albe", VarC = "Plachete sanguine", RaspunsCorect = 3 },
new Question { Text = "Care este cea mai mare celulă din organismul uman?", VarA = "Ovarul", VarB = "Ovulul", VarC = "Testicolul", RaspunsCorect = 2 },
new Question { Text = "Ce organ din corpul uman este responsabil pentru producerea sângelui?", VarA = "Inima", VarB = "Ficatul", VarC = "Măduva oaselor", RaspunsCorect = 3 },
new Question { Text = "Cum se numește procesul prin care plantele absorb apă din sol?", VarA = "Evaporație", VarB = "Transpirație", VarC = "Absorbție", RaspunsCorect = 3 },
new Question { Text = "Câte picioare are o muscă?", VarA = "6", VarB = "4", VarC = "8", RaspunsCorect = 1 },
new Question { Text = "Ce parte a sistemului nervos este responsabilă pentru coordonarea mișcărilor?", VarA = "Creierul", VarB = "Măduva spinării", VarC = "Nervii periferici", RaspunsCorect = 1 },
new Question { Text = "Care sunt organele reproductive ale unei flori?", VarA = "Rizomii", VarB = "Pistilul și stamina", VarC = "Filamentul și antera", RaspunsCorect = 2 },
new Question { Text = "Ce sunt enzimele?", VarA = "Proteine care accelerează reacțiile chimice", VarB = "Carbohidrați", VarC = "Lipide", RaspunsCorect = 1 },
new Question { Text = "Ce molecule sunt considerate \"monomeri\" ai proteinelor?", VarA = "Aminoacizi", VarB = "Nucleotide", VarC = "Zaharuri", RaspunsCorect = 1 },
new Question { Text = "Care este funcția principală a sistemului excretor?", VarA = "Menținerea echilibrului hidric", VarB = "Respirația", VarC = "Digestia alimentelor", RaspunsCorect = 1 },
new Question { Text = "Ce tip de ADN este responsabil pentru transmiterea caracteristicilor ereditare?", VarA = "ADN mitocondrial", VarB = "ADN nuclear", VarC = "ADN plasmidic", RaspunsCorect = 2 },
new Question { Text = "Ce organ din corpul uman este responsabil pentru filtrarea sângelui?", VarA = "Plămânii", VarB = "Ficatul", VarC = "Rinichii", RaspunsCorect = 3 },
//143

new Question { Text = "Arcul de Triumf din București se află în sectorul:", VarA = "Unu", VarB = "Doi", VarC = "Cinci", RaspunsCorect = 1 },
new Question { Text = "Ce este un IP?", VarA = "Internet Protocol", VarB = "Internet Provider", VarC = "Internet Procedure", RaspunsCorect = 1 },
new Question { Text = "Ce reprezintă RAM?", VarA = "Random Access Memory", VarB = "Read Access Memory", VarC = "Read And Modify", RaspunsCorect = 1 },
new Question { Text = "Câți centimetrii are un inch?", VarA = "2,54", VarB = "25,4", VarC = "0,25", RaspunsCorect = 1 },
new Question { Text = "Ce este o adresă MAC?", VarA = "Media Access Control", VarB = "Memory Address Control", VarC = "Main Access Control", RaspunsCorect = 1 },
new Question { Text = "Ce combinație de taste este folosită pentru revenirea pe desktop?", VarA = "windows+d", VarB = "alt+d", VarC = "ctrl+d", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă IoT?", VarA = "Internet of Tools", VarB = "Internet of Things", VarC = "Internet of Technology", RaspunsCorect = 2 },
new Question { Text = "Când avem deschisa o fereastră Chrome, ce combinație de taste folosim pentru focalizarea în bara de adrese și de căutare?", VarA = "alt+f", VarB = "alt+d", VarC = "windows+d", RaspunsCorect = 2 },
new Question { Text = "În cadrul limbajelor de programare, o instrucțiune iterativă este:", VarA = "if", VarB = "switch", VarC = "for", RaspunsCorect = 3 },
new Question { Text = "Ce reprezintă BIOS?", VarA = "Basic Input/Output System", VarB = "Binary Input/Output System", VarC = "Basic Internal Operating System", RaspunsCorect = 1 },
new Question { Text = "Ce este un server?", VarA = "Un dispozitiv de stocare", VarB = "Un program de calcul tabelar", VarC = "Un sistem care furnizează servicii altor computere", RaspunsCorect = 3 },
new Question { Text = "Ce este o bază de date?", VarA = "Un sistem de operare", VarB = "O colecție organizată de date", VarC = "Un software de grafică", RaspunsCorect = 2 },
new Question { Text = "Ce reprezintă termeni \"frontend\" și \"backend\" în dezvoltarea web?", VarA = "Design și conținut", VarB = "Interfață și server", VarC = "Hardware și software", RaspunsCorect = 2 },
new Question { Text = "Ce este un algoritm?", VarA = "O serie de instrucțiuni pentru a rezolva o problemă", VarB = "Un dispozitiv de stocare", VarC = "Un program de editare video", RaspunsCorect = 1 },
new Question { Text = "Ce este un cookie în contextul internetului?", VarA = "O mică fișier de date stocat pe computerul utilizatorului", VarB = "O aplicație de chat", VarC = "Un tip de virus", RaspunsCorect = 1 },
new Question { Text = "Ce este un API?", VarA = "Application Programming Interface", VarB = "Application Programming Instruction", VarC = "Advanced Programming Interface", RaspunsCorect = 1 },
new Question { Text = "Ce este o rețea LAN?", VarA = "Local Area Network", VarB = "Large Area Network", VarC = "Local Access Network", RaspunsCorect = 1 },
new Question { Text = "Ce reprezintă sigla USB?", VarA = "Universal Serial Bus", VarB = "Universal Storage Bus", VarC = "Unified Serial Bus", RaspunsCorect = 1 },
new Question { Text = "Ce este un virus informatic?", VarA = "Un program care reproduce și infectează alte programe", VarB = "Un software de securitate", VarC = "O aplicație de editare", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă VPN?", VarA = "Virtual Private Network", VarB = "Virtual Public Network", VarC = "Virtual Protected Network", RaspunsCorect = 1 },
new Question { Text = "Ce este un modem?", VarA = "Un dispozitiv care permite accesul la internet", VarB = "Un software de editare video", VarC = "Un program antivirus", RaspunsCorect = 1 },
new Question { Text = "Ce este un browser web?", VarA = "Un program pentru navigarea pe internet", VarB = "Un sistem de operare", VarC = "Un software de grafică", RaspunsCorect = 1 },
new Question { Text = "Ce este phishing?", VarA = "O tentativă de a obține informații sensibile prin fraudă", VarB = "Un tip de software antivirus", VarC = "O metodă de backup", RaspunsCorect = 1 },
new Question { Text = "Ce combinație de taste este utilizată pentru închiderea unei aplicații Windows?", VarA = "ctrl+q", VarB = "ctrl+f4", VarC = "alt+f4", RaspunsCorect = 3 },
new Question { Text = "Ce este un bug în contextul software?", VarA = "O eroare sau defect în program", VarB = "Un software de securitate", VarC = "Un tip de aplicație", RaspunsCorect = 1 },
new Question { Text = "Ce se utilizează pentru ca pe ecranul iPhoneului fără buton home să apară fereastra de închidere a dispozitivului?", VarA = "power și vol + apoi vol -", VarB = "apăsarea 5 secunde power", VarC = "power+vol+", RaspunsCorect = 1 },
new Question { Text = "Ce este machine learning?", VarA = "Un tip de inteligență artificială care permite calculatoarelor să învețe din date", VarB = "Un software de editare video", VarC = "Un tip de rețea de calculatoare", RaspunsCorect = 1 }
//170




            };
        }
    }
}
