using System.Collections.Generic;
using LearnGame26.Pages; 

namespace LearnGame26.Pages
{
    public static class QuestionList3
    {
        public static List<Question> GetQuestions()
        {
            return new List<Question>
            {

new Question { Text = "Ca procese psihice, senzațiile se produc:", VarA = "în absența acțiunii stimulului asupra simțurilor", VarB = "în urma perceperii repetate a obiectelor", VarC = "prin acțiunea directă a stimulului asupra simțurilor", RaspunsCorect = 3 },
new Question { Text = "Senzațiile tactile și cele termice sunt senzații:", VarA = "vizuale", VarB = "cutanate", VarC = "olfactive", RaspunsCorect = 2 },
new Question { Text = "Care este prima etapă a memorării?", VarA = "întipărirea", VarB = "păstrarea", VarC = "reactualizarea", RaspunsCorect = 1 },
new Question { Text = "Care dintre situațiile de mai jos necesită memorare logică?", VarA = "numerele de telefon", VarB = "datele istorice", VarC = "formulele matematice", RaspunsCorect = 3 },
new Question { Text = "Uneori unele informații nu mai pot fi reactualizate. Ce s-a întâmplat cu ele?", VarA = "sunt în inconștient", VarB = "sunt în memoria de lungă durată", VarC = "sunt în memoria de scurtă durată", RaspunsCorect = 1 },
new Question { Text = "Piramida trebuințelor umane a fost realizată de:", VarA = "Jean Piaget", VarB = "Howard Gardner", VarC = "Abraham Maslow", RaspunsCorect = 3 },
new Question { Text = "Cum este caracterul?", VarA = "Dobândit", VarB = "Înăscut", VarC = "Formativ", RaspunsCorect = 1 },
new Question { Text = "Cum este temperamentul?", VarA = "Înăscut", VarB = "Dobândit", VarC = "Creativ", RaspunsCorect = 1 },
new Question { Text = "Câte tipuri de temperament există?", VarA = "5", VarB = "4", VarC = "3", RaspunsCorect = 2 },

new Question { Text = "Ce formează împreună temperamentul și caracterul?", VarA = "Atitudinea", VarB = "Aptitudinea", VarC = "Personalitatea", RaspunsCorect = 3 },
new Question { Text = "Cine este fondatorul psihologiei analitice?", VarA = "Sigmund Freud", VarB = "Carl Jung", VarC = "Jean Piaget", RaspunsCorect = 2 },
new Question { Text = "Ce tip de procese sunt motivația și voința?", VarA = "Cognitive", VarB = "Primare", VarC = "Afectiv-volitive", RaspunsCorect = 3 },
new Question { Text = "De câte tipuri este motivația?", VarA = "Intrinsecă-extrinsecă", VarB = "Voluntară-involuntară", VarC = "Formativă-informativă", RaspunsCorect = 1 },
new Question { Text = "Ce formează conștientul, subconștientul și inconștientul?", VarA = "Mintea umană", VarB = "Procesele psihice", VarC = "Gândirea", RaspunsCorect = 1 },
new Question { Text = "Cum este memoria?", VarA = "Intrinsecă-extrinsecă", VarB = "Voluntară-involuntară", VarC = "Conștientă-inconștientă", RaspunsCorect = 2 },
new Question { Text = "Ce tip de procese sunt gândirea și limbajul?", VarA = "Afectiv-volitive", VarB = "Primare", VarC = "Cognitive", RaspunsCorect = 3 },
new Question { Text = "La ce parte de vorbire se analizează genul?", VarA = "Verbul", VarB = "Adverbul", VarC = "Substantivul", RaspunsCorect = 3 },
new Question { Text = "Ce caz răspunde la întrebarea cine?", VarA = "Dativ", VarB = "Acuzativ", VarC = "Nominativ", RaspunsCorect = 3 },

new Question { Text = "Ce caz răspunde la întrebarea cui?", VarA = "Genitiv", VarB = "Dativ", VarC = "Acuzativ", RaspunsCorect = 2 },
new Question { Text = "Ce caz exprimă un îndemn, o poruncă?", VarA = "Vocativ", VarB = "Dativ", VarC = "Genitiv", RaspunsCorect = 1 },
new Question { Text = "Ce parte de vorbire este cuvântul cra?", VarA = "Conjuncția", VarB = "Interjecția", VarC = "Prepoziția", RaspunsCorect = 2 },
new Question { Text = "Ce parte de vorbire exprimă o însușire?", VarA = "Adverbul", VarB = "Verbul", VarC = "Adjectivul", RaspunsCorect = 3 },
new Question { Text = "Ce funcție sintactică răspunde la întrebarea pe cine?", VarA = "Complementul indirect", VarB = "Complementul direct", VarC = "Subiectul", RaspunsCorect = 2 },
new Question { Text = "Ca să pui întrebarea și să-ți răspundă un atribut, trebuie să întrebi:", VarA = "Verbul", VarB = "Adjectivul", VarC = "Substantivul", RaspunsCorect = 3 },
new Question { Text = "Ca să răspundă un complement trebuie să pui întrebarea unui:", VarA = "Verb", VarB = "Substantiv", VarC = "Adjectiv", RaspunsCorect = 1 },
new Question { Text = "La ce mod și ce timp este verbul am vorbit?", VarA = "Conjunctiv-perfect", VarB = "Indicativ-trecut", VarC = "Indicativ-perfect compus", RaspunsCorect = 3 },
new Question { Text = "La ce mod și ce timp este verbul aș fi mers?", VarA = "Condițional optativ-perfect", VarB = "Condițional optativ-prezent", VarC = "Conjunctiv-prezent", RaspunsCorect = 1 },
new Question { Text = "Un exemplu de verb la gerunziu este:", VarA = "Merseseră", VarB = "De mers", VarC = "Mergând", RaspunsCorect = 3 },
new Question { Text = "Un exemplu de verb la infinitiv este:", VarA = "Am fost", VarB = "A fi", VarC = "A fost", RaspunsCorect = 2 },
new Question { Text = "La ce întrebare răspunde complementul circumstanțial de mod?", VarA = "unde", VarB = "Cum", VarC = "Când", RaspunsCorect = 2 },
new Question { Text = "Câte părți de vorbire există în limba română?", VarA = "8", VarB = "9", VarC = "10", RaspunsCorect = 3 },
new Question { Text = "Adjectivul 'la fel de rapid' este la gradul de comparație:", VarA = "Comparativ de superioritate", VarB = "Superlativ relativ", VarC = "Comparativ de egalitate", RaspunsCorect = 3 },
new Question { Text = "Care dintre următoarele adjective este la gradul superlativ relativ?", VarA = "Cel mai frumos", VarB = "Foarte frumos", VarC = "Mai frumos", RaspunsCorect = 1 },
new Question { Text = "Cu ce planetă este adesea comparat Luceafărul?", VarA = "Marte", VarB = "Venus", VarC = "Saturn", RaspunsCorect = 2 },
new Question { Text = "Care este numele atribuit Luceafărului în poezia cu aceeași denumire?", VarA = "Hiperion", VarB = "Cătălin", VarC = "Părintele ceresc", RaspunsCorect = 1 },
new Question { Text = "Ce se întâmplă în finalul operei Iona scrisă de Marin Sorescu?", VarA = "Iona ajunge în burta unui pește", VarB = "Iona naufragiază", VarC = "Iona se sinucide", RaspunsCorect = 3 },
new Question { Text = "Care este principala temă din opera Plumb scrisă de George Bacovia?", VarA = "Moartea", VarB = "Natura", VarC = "Istoria", RaspunsCorect = 1 },

new Question { Text = "Ca figură de stil, ce este hiperbola?", VarA = "O alegorie", VarB = "O exagerare", VarC = "Un adevăr susținut", RaspunsCorect = 2 },
new Question { Text = "Ce înseamnă că un personaj este eponim?", VarA = "Dă numele operei", VarB = "Este personajul principal", VarC = "Este personaj pozitiv", RaspunsCorect = 1 },
new Question { Text = "Cum o chema pe soția lui Ion în romanul cu același nume?", VarA = "Florica", VarB = "Zenobia", VarC = "Ana", RaspunsCorect = 3 },
new Question { Text = "Câte etape de creație a avut Ion Barbu?", VarA = "3", VarB = "2", VarC = "4", RaspunsCorect = 1 },
new Question { Text = "Cum sunt grupate versurile în cazul rimei încrucișate?", VarA = "1 cu 2 și 3 cu 4", VarB = "1 cu 3 și 2 cu 4", VarC = "1 cu 4 și 2 cu 3", RaspunsCorect = 2 },
new Question { Text = "În cadrul operelor dramatice, ce sunt didascaliile?", VarA = "Replici", VarB = "Prezentarea actorilor", VarC = "Paranteze regizorale", RaspunsCorect = 3 },
new Question { Text = "Cum îl cheamă pe câinele care îl apără uneori pe Jerry de Tom?", VarA = "Tike", VarB = "Spike", VarC = "Butch", RaspunsCorect = 2 },
new Question { Text = "Cum îl cheamă pe motanul portocaliu care prinde șoareci în locul lui Tom?", VarA = "Fulger", VarB = "Pecos", VarC = "Tike", RaspunsCorect = 1 },
new Question { Text = "Cum îl cheamă pe câinele care apare adesea în seria Pistruiatul?", VarA = "Lupu", VarB = "Puricilă", VarC = "Calu", RaspunsCorect = 3 },
new Question { Text = "Din câte episoade este alcătuit serialul Pistruiatul?", VarA = "5", VarB = "8", VarC = "10", RaspunsCorect = 3 },
new Question { Text = "În serialul cu același nume, cum îl cheamă pe personajul Pistruiatul?", VarA = "Mihai Pleșa", VarB = "Andrei Pleșa", VarC = "Ștefan Pleșa", RaspunsCorect = 1 },
new Question { Text = "În seria Pistruiatul ce mare actriță a jucat rolul doamnei Rozeanu?", VarA = "Tamara Buciuceanu", VarB = "Draga Olteanu", VarC = "Rodica Popescu", RaspunsCorect = 2 },
new Question { Text = "De ce a murit actorul Toma Caragiu?", VarA = "Bătrânețe", VarB = "Accident de mașină", VarC = "Cutremur", RaspunsCorect = 3 },
new Question { Text = "În ce an a murit actorul Jean Constantin?", VarA = "1977", VarB = "2010", VarC = "2005", RaspunsCorect = 2 },
new Question { Text = "Cine este personajul principal din seria bobocilor?", VarA = "Horațiu Mălăiele", VarB = "Puiu Călinescu", VarC = "Dem Rădulescu", RaspunsCorect = 1 },
new Question { Text = "Care dintre următorii actori nu a jucat în seria Brigada Diverse?", VarA = "Sebastian Papaiani", VarB = "Toma Caragiu", VarC = "Amza Pelea", RaspunsCorect = 3 },
new Question { Text = "Orașul Geneva se află în statul numit:", VarA = "Austria", VarB = "Germania", VarC = "Elveția", RaspunsCorect = 3 },
new Question { Text = "Cel mai mare oraș din China este:", VarA = "Tokyo", VarB = "Shanghai", VarC = "Kyoto", RaspunsCorect = 2 },
new Question { Text = "Ce peninsulă formează Spania și Portugalia?", VarA = "Balcanică", VarB = "Iberică", VarC = "Scandinavă", RaspunsCorect = 2 },
new Question { Text = "Între America și Europa se află oceanul:", VarA = "Atlantic", VarB = "Pacific", VarC = "Indian", RaspunsCorect = 1 },
//57

new Question { Text = "Ce ministat se află în Roma, capitala Italiei?", VarA = "Monaco", VarB = "San Marino", VarC = "Vatican", RaspunsCorect = 3 },
new Question { Text = "Pe ce continent se află munții Apalași?", VarA = "Europa", VarB = "America de Nord", VarC = "America de Sud", RaspunsCorect = 2 },
new Question { Text = "Câte lacuri mari se află în America de Nord?", VarA = "5", VarB = "4", VarC = "3", RaspunsCorect = 1 },
new Question { Text = "Care dintre următoarele state se află pe două continente?", VarA = "Grecia", VarB = "Turcia", VarC = "Macedonia", RaspunsCorect = 2 },
new Question { Text = "Localitatea Humulești se află în județul:", VarA = "Botoșani", VarB = "Iași", VarC = "Neamț", RaspunsCorect = 3 },
new Question { Text = "În ce județ se află orașul Cracii Doamnei?", VarA = "Vâlcea", VarB = "Argeș", VarC = "Brașov", RaspunsCorect = 1 },
new Question { Text = "Cu ce se ocupă ornitologia?", VarA = "Studiul peștilor", VarB = "Studiul peșterilor", VarC = "Studiul păsărilor", RaspunsCorect = 3 },
new Question { Text = "Cu ce se ocupă speologia?", VarA = "Studiul păsărilor", VarB = "Studiul planetelor", VarC = "Studiul peșterilor", RaspunsCorect = 3 },
new Question { Text = "Unde a locuit Vasile Alexandri, locul fiind menționat și în poeziile sale?", VarA = "Haimanale", VarB = "Mircești", VarC = "Iași", RaspunsCorect = 2 },
new Question { Text = "Câte muchii are o piramidă?", VarA = "4", VarB = "6", VarC = "8", RaspunsCorect = 3 },
new Question { Text = "Care era vechea denumire a Dunării?", VarA = "Danubius", VarB = "Ponticus", VarC = "Malus", RaspunsCorect = 1 },
new Question { Text = "Câți ani a trăit Mihai Eminescu?", VarA = "49", VarB = "39", VarC = "33", RaspunsCorect = 2 },
new Question { Text = "Ce fel de operă este Alexandru Lăpușneanu?", VarA = "Psihologică", VarB = "Comică", VarC = "Istorică", RaspunsCorect = 3 },
new Question { Text = "Care este capitala Macedoniei?", VarA = "Skopje", VarB = "Minsk", VarC = "Priștina", RaspunsCorect = 1 },
new Question { Text = "Ce stat are capitala la Pristina?", VarA = "Georgia", VarB = "Kosovo", VarC = "Muntenegru", RaspunsCorect = 2 },
new Question { Text = "În ce este divizată Elveția?", VarA = "Landuri", VarB = "Cantoane", VarC = "Provincii", RaspunsCorect = 2 },

new Question { Text = "Cum se numesc subdiviziunile Germaniei?", VarA = "Cantoane", VarB = "Provincii", VarC = "Landuri", RaspunsCorect = 3 },
new Question { Text = "Ce țară din Europa are o infrastructură foarte dezvoltată pentru biciclete?", VarA = "Norvegia", VarB = "Olanda", VarC = "Danemarca", RaspunsCorect = 2 },
new Question { Text = "Ce este un tapir?", VarA = "Un animal", VarB = "Un tip de hârtie", VarC = "O unealtă", RaspunsCorect = 1 },
new Question { Text = "Ce culoare are steagul Italiei?", VarA = "Verde, alb, roșu", VarB = "Albastru, alb, roșu", VarC = "verde, galben, roșu", RaspunsCorect = 1 },
new Question { Text = "Ce culoare are steagul Franței?", VarA = "Verde, alb, roșu", VarB = "Mov, alb, roșu", VarC = "Albastru, alb, roșu", RaspunsCorect = 3 },
new Question { Text = "Ce element organic apare pe steagul Canadei?", VarA = "O frunză de stejar", VarB = "O frunză de arțar", VarC = "O ghindă", RaspunsCorect = 2 },
new Question { Text = "Câte stele sunt pe drapelul Uniunii Europene?", VarA = "50", VarB = "12", VarC = "23", RaspunsCorect = 2 },
new Question { Text = "Câte stele se află pe steagul Statelor Unite?", VarA = "49", VarB = "50", VarC = "13", RaspunsCorect = 2 },
new Question { Text = "Ingredientul principal din Tiramisu este:", VarA = "Mascarpone", VarB = "Frișcă", VarC = "Oul", RaspunsCorect = 1 },
new Question { Text = "Pentru a neutraliza mirosul de pește de pe mâini se utilizează:", VarA = "Oțetul", VarB = "Lămâia", VarC = "Ceaiul de urzică", RaspunsCorect = 2 },
new Question { Text = "Cum este înțepătura de viespe?", VarA = "Acidă", VarB = "Neutră", VarC = "Alcalină", RaspunsCorect = 3 },
new Question { Text = "Care nu este remediul pentru înțepătura de viespe?", VarA = "Oțetul", VarB = "Bicarbonatul de sodiu", VarC = "Lămâia", RaspunsCorect = 2 },
new Question { Text = "Nu este un tratament recomandat în cazul înțepăturilor de albine:", VarA = "Oțetul", VarB = "Pătrunjelul", VarC = "Sarea de bucătărie", RaspunsCorect = 1 },
//86

new Question { Text = "Care este cel mai mare deșert cald din lume?", VarA = "Deșertul Gobi", VarB = "Deșertul Sahara", VarC = "Deșertul Kalahari", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai mare arhipelag din lume?", VarA = "Arhipelagul Indonezian", VarB = "Arhipelagul Chagos", VarC = "Arhipelagul Mergui", RaspunsCorect = 1 },
new Question { Text = "Care este cel mai adânc lac din lume?", VarA = "Lacul Tanganyika", VarB = "Lacul Baikal", VarC = "Lacul Vostok", RaspunsCorect = 2 },
new Question { Text = "Care au fost țările membre ale Axei în timpul celui de-al Doilea Război Mondial?", VarA = "Germania, Rusia și Turcia", VarB = "Germania, Austria și Turcia", VarC = "Germania, Italia și Japonia", RaspunsCorect = 3 },
new Question { Text = "Care a fost evenimentul care a marcat începutul Revoluției Franceze?", VarA = "Decapitarea regelui", VarB = "Preluarea puterii de către Napoleon", VarC = "Căderea Bastiliei", RaspunsCorect = 3 },
new Question { Text = "Care a fost liderul sovietic responsabil pentru Glasnost și Perestroika?", VarA = "Mihail Gorbaciov", VarB = "Iosiv V. Stalin", VarC = "Nikita Hrușciov", RaspunsCorect = 1 },
new Question { Text = "Cine a fost liderul African National Congress (ANC) și primul președinte al Africii de Sud?", VarA = "Robert Mugabe", VarB = "Nelson Mandela", VarC = "Mahatma Gandhi", RaspunsCorect = 2 },
new Question { Text = "Cine este considerat fondatorul religiei islamice?", VarA = "Profetul Muhammad", VarB = "Mahatma Gandhi", VarC = "Regele David", RaspunsCorect = 1 },
new Question { Text = "Care este cartea sacră a religiei iudaice?", VarA = "Coranul", VarB = "Tora", VarC = "Diwali", RaspunsCorect = 2 },
new Question { Text = "Care este zeul suprem al religiei hinduse?", VarA = "Brahman", VarB = "Zeus", VarC = "Alah", RaspunsCorect = 1 },
new Question { Text = "Cine a marcat cele mai multe goluri într-un singur sezon de fotbal dintr-un campionat european?", VarA = "Gheorghe Hagi", VarB = "Maradona", VarC = "Lionel Messi", RaspunsCorect = 3 },
new Question { Text = "Ce naționalitate avea legendarul baschetbalist Michael Jordan?", VarA = "Engleză", VarB = "Americană", VarC = "Australiană", RaspunsCorect = 2 },
new Question { Text = "Ce jucător de tenis a câștigat cele mai multe turnee de Grand Slam la masculin?", VarA = "Jack Nicklaus", VarB = "Tiger Woods", VarC = "Arnold Palmer", RaspunsCorect = 1 },
new Question { Text = "Ce țară a câștigat cel mai mare număr de medalii de aur la Jocurile Olimpice de vară din 2016?", VarA = "China", VarB = "Canada", VarC = "S.U.A.", RaspunsCorect = 3 },
new Question { Text = "În ce țară se află cel mai mare stadion de fotbal din lume după capacitate?", VarA = "Germania", VarB = "Coreea de Nord", VarC = "Brazilia", RaspunsCorect = 2 },
new Question { Text = "Care este sportul care are cele mai multe medalii de aur acordate la Jocurile Olimpice de vară?", VarA = "Gimnastica", VarB = "Natația", VarC = "Scrima", RaspunsCorect = 2 },
new Question { Text = "Cine a compus opera “La Traviata”?", VarA = "Giuseppe Verdi", VarB = "Antonín Dvořák", VarC = "Ludwig van Beethoven", RaspunsCorect = 1 },
new Question { Text = "Care este cel mai lung roman scris în limba română?", VarA = "Cireșarii", VarB = "Frații Jderi", VarC = "La răscruce de vânturi", RaspunsCorect = 3 },
new Question { Text = "Ce este un sonet?", VarA = "Un poem alcătuit din 14 versuri, cu rime și structură fixă", VarB = "Un poem alcătuit din 4 catrene", VarC = "Un poem cu rimă albă", RaspunsCorect = 1 },
new Question { Text = "Care instrument este cunoscut ca regele instrumentelor?", VarA = "Vioara", VarB = "Orga", VarC = "Pianul", RaspunsCorect = 2 },
new Question { Text = "Care este ingredientul principal din guacamole?", VarA = "Papaia", VarB = "Avocado", VarC = "Guava", RaspunsCorect = 2 },
new Question { Text = "Ce mâncare specifică este considerată un simbol al bucătăriei mexicane?", VarA = "Tacos", VarB = "Nachos", VarC = "Tortellini", RaspunsCorect = 1 },
new Question { Text = "Cine a pictat Cina cea de taină?", VarA = "Rembrandt", VarB = "Van Gogh", VarC = "Leonardo da Vinci", RaspunsCorect = 3 },

new Question { Text = "Ce țară este supranumită Țara Cimitirelor?", VarA = "Egipt", VarB = "Corea de Nord", VarC = "Irak", RaspunsCorect = 1 },
new Question { Text = "În ce țară se află monumentul Stonehenge?", VarA = "Anglia", VarB = "Hawaii", VarC = "Insula Paștelui", RaspunsCorect = 1 },
new Question { Text = "Cine a scris Odiseea?", VarA = "Herodot", VarB = "Homer", VarC = "Euripides", RaspunsCorect = 2 },
new Question { Text = "Care este unitatea de măsură pentru forța în Sistemul Internațional?", VarA = "Joule", VarB = "Ohm", VarC = "Newton", RaspunsCorect = 3 },
new Question { Text = "Ce tip de celule sanguine sunt responsabile pentru coagularea sângelui?", VarA = "Trombocitele", VarB = "Leucocitele", VarC = "Hematiile", RaspunsCorect = 1 },
new Question { Text = "Ce tip de particule subatomice transportă sarcina electrică negativă?", VarA = "Protonii", VarB = "Electronii", VarC = "Neutronii", RaspunsCorect = 2 },
new Question { Text = "Care este capitala Nepalului?", VarA = "Baku", VarB = "Kathmandu", VarC = "Damasc", RaspunsCorect = 2 },
new Question { Text = "Ce oraș a fost cunoscut în antichitate ca Byzantium?", VarA = "Istanbul", VarB = "Ancara", VarC = "Antalya", RaspunsCorect = 1 },
new Question { Text = "Care este cel mai vechi instrument muzical cunoscut?", VarA = "Toba", VarB = "Vioara", VarC = "Flautul", RaspunsCorect = 3 },
new Question { Text = "În ce oraș se află faimosul Muzeu Luvru?", VarA = "Paris", VarB = "Marsilia", VarC = "Lyon", RaspunsCorect = 1 },
new Question { Text = "Care este cel mai sudic oraș din România?", VarA = "Giurgiu", VarB = "Zimnicea", VarC = "Tulcea", RaspunsCorect = 2 },
new Question { Text = "Cu ce scriitor l-ar fi înșelat Veronica Micle pe Mihai Eminescu?", VarA = "Ion Creangă", VarB = "Ion Luca Caragiale", VarC = "Titu Maiorescu", RaspunsCorect = 2 },
new Question { Text = "Cu ce state se învecinează Statele Unite ale Americii?", VarA = "Mexic și Canada", VarB = "Canada și Texas", VarC = "Mexic și Texas", RaspunsCorect = 1 },
new Question { Text = "Câți copii are regele Charles al Marii Britanii?", VarA = "Trei", VarB = "Unul", VarC = "Doi", RaspunsCorect = 3 },
new Question { Text = "Ce râu important traversează Egipt?", VarA = "Nilul", VarB = "Ebru", VarC = "Gange", RaspunsCorect = 1 },
new Question { Text = "În ce țară s-a născut Adolf Hitler?", VarA = "Germania", VarB = "Austria", VarC = "Danemarca", RaspunsCorect = 2 },
new Question { Text = "Cine a compus Nunta lui Figaro?", VarA = "Mozart", VarB = "Bach", VarC = "Beethoven", RaspunsCorect = 1 },
new Question { Text = "Din ce oraș provenea Thales?", VarA = "Alexandria", VarB = "Cartagina", VarC = "Milet", RaspunsCorect = 3 },
new Question { Text = "Câți apostoli avea Iisus Hristos?", VarA = "11", VarB = "6", VarC = "12", RaspunsCorect = 3 },
new Question { Text = "Care este cea mai mare insulă din lume?", VarA = "Creta", VarB = "Groenlanda", VarC = "Honshu", RaspunsCorect = 2 },
new Question { Text = "Câți dinți are un om?", VarA = "32", VarB = "64", VarC = "16", RaspunsCorect = 1 },
new Question { Text = "În ce an a câștigat Toto Cutugno concursul Eurovision?", VarA = "1990", VarB = "1981", VarC = "1999", RaspunsCorect = 1 },
new Question { Text = "În ce țară se află Taj Mahal?", VarA = "India", VarB = "Turcia", VarC = "Arabia", RaspunsCorect = 1 },
new Question { Text = "Care este cel mai sudic braț al Dunării din România?", VarA = "Chilia", VarB = "Sfântul Gheorghe", VarC = "Sulina", RaspunsCorect = 2 },
//133

new Question { Text = "Câți ani are un deceniu?", VarA = "10", VarB = "100", VarC = "1000", RaspunsCorect = 1 },
new Question { Text = "Care sunt culorile echipei de fotbal Dinamo București?", VarA = "Galben și albastru", VarB = "Roșu și alb", VarC = "Roșu și galben", RaspunsCorect = 2 },
new Question { Text = "Care sunt culorile clubului Barcelona?", VarA = "Roșu și negru", VarB = "Roșu și alb", VarC = "Roșu și albastru", RaspunsCorect = 3 },
new Question { Text = "Cum se numește un unghi de 120 de grade?", VarA = "Obtuz", VarB = "Ascuțit", VarC = "Drept", RaspunsCorect = 1 },
new Question { Text = "Care este orașul în care a murit sculptorul Constantin Brâncuși?", VarA = "Târgu-Jiu", VarB = "Paris", VarC = "București", RaspunsCorect = 2 },
new Question { Text = "În ce țară a fost inventată Coca Cola?", VarA = "Statele Unite ale Americii", VarB = "Norvegia", VarC = "Suedia", RaspunsCorect = 1 },
new Question { Text = "În ce an a murit Prințesa Diana?", VarA = "1997", VarB = "1989", VarC = "2001", RaspunsCorect = 1 },
new Question { Text = "Cine a scris poezia Repetabila povară?", VarA = "George Bacovia", VarB = "Nichita Stănescu", VarC = "Adrian Păunescu", RaspunsCorect = 3 },
new Question { Text = "Muammar Gaddafi a fost conducătorul cărei ţări între anii 1969 şi 2011?", VarA = "Libia", VarB = "Liban", VarC = "Irak", RaspunsCorect = 1 },
new Question { Text = "În ce judeţ se află localitatea Roşia Montană?", VarA = "Alba", VarB = "Neamț", VarC = "Bihor", RaspunsCorect = 1 },
new Question { Text = "În ce oraș se află cea mai veche pizzerie din lume?", VarA = "Napoli", VarB = "Toronto", VarC = "Milano", RaspunsCorect = 1 },
new Question { Text = "De unde sunt originare sarmalele?", VarA = "România", VarB = "Turcia", VarC = "Serbia", RaspunsCorect = 2 },
new Question { Text = "Cine a scris Hansel și Gretel?", VarA = "Hans Cristian Andersen", VarB = "Thomas Mann", VarC = "Frații Grimm", RaspunsCorect = 3 },
new Question { Text = "La ce vârstă a fost crucificat Iisus Hristos?", VarA = "39 de ani", VarB = "30 de ani", VarC = "33 de ani", RaspunsCorect = 3 },
new Question { Text = "Ce înseamnă I.N.R.I.?", VarA = "Iisus din Nazareth, Regele Iudeilor", VarB = "Iisus Nazarineanul, regele iudaismului", VarC = "Iisus din Nazaret, regele iertător", RaspunsCorect = 1 },
new Question { Text = "La ce război a participat Ioana d’Arc?", VarA = "La războaiele prusace", VarB = "La războiul de 100 de ani", VarC = "La războaiele Napoleoniene", RaspunsCorect = 2 },
new Question { Text = "Care era capitala Daciei înainte de invazia romanilor?", VarA = "Sarmisegetuza", VarB = "Căpâlna", VarC = "Ulpia Traiana Sarmisegetuza", RaspunsCorect = 1 },
new Question { Text = "În ce țară au fost cultivate pentru prima dată portocalele?", VarA = "China", VarB = "Africa de Nord", VarC = "Coasta de Fildeș", RaspunsCorect = 1 },
new Question { Text = "Cărei țări aparține insula Corsica?", VarA = "Franța", VarB = "Italia", VarC = "Spania", RaspunsCorect = 1 },
new Question { Text = "Care este fotbalistul român cu cele mai multe selecții la echipa națională a României?", VarA = "Dorinel Munteanu", VarB = "Lăcătuș", VarC = "Gică Hagi", RaspunsCorect = 1 },
new Question { Text = "Care este primul stat european unde s-a construit o autostradă?", VarA = "Anglia", VarB = "Norvegia", VarC = "Germania", RaspunsCorect = 3 },
new Question { Text = "Care este cea mai populată țară din lume?", VarA = "China", VarB = "India", VarC = "Rusia", RaspunsCorect = 2 },
new Question { Text = "În ce țară se află canalul Suez?", VarA = "Egipt", VarB = "Arabia Saudită", VarC = "Iran", RaspunsCorect = 1 },
new Question { Text = "În ce județ se află salina Turda?", VarA = "Maramureș", VarB = "Cluj", VarC = "Bistrița", RaspunsCorect = 2 },
new Question { Text = "În ce țară se află lacul Balaton?", VarA = "Bulgaria", VarB = "Serbia", VarC = "Ungaria", RaspunsCorect = 3 },
new Question { Text = "Cum se numește lacul cu cea mai mare suprafață din România?", VarA = "Lacul Razim", VarB = "Lacul Zănoaga Mare", VarC = "Lacul Vidraru", RaspunsCorect = 1 },
new Question { Text = "În ce județ se află Vulcanii Noroioși?", VarA = "Argeș", VarB = "Buzău", VarC = "Ialomița", RaspunsCorect = 2 },
new Question { Text = "Ce țară deține Insula Șerpilor?", VarA = "România", VarB = "Ucraina", VarC = "Rusia", RaspunsCorect = 2 },
new Question { Text = "În ce oraș poate fi vizitată Sagrada Familia?", VarA = "Barcelona", VarB = "Napoli", VarC = "Roma", RaspunsCorect = 1 },
new Question { Text = "Care este imnul oficial al Franței?", VarA = "La Marcha Real", VarB = "La Marseillaise", VarC = "Mazurca lui Dombrowski", RaspunsCorect = 2 },
new Question { Text = "Care a fost imnul de stat al României înainte de Deșteaptă-te, române?", VarA = "Slăbite cătușe", VarB = "Te slăvim Românie", VarC = "Trei culori", RaspunsCorect = 3 },
new Question { Text = "Ce culoare are cutia neagră a unui avion?", VarA = "Portocalie", VarB = "Neagră", VarC = "Gri", RaspunsCorect = 1 },
new Question { Text = "Ce formă de guvernământ se află în Regatul Unit?", VarA = "Monarhie", VarB = "Monarhie constituțională", VarC = "Monarhie autoritară", RaspunsCorect = 2 },
new Question { Text = "Un produs costă 80 de lei. Se scumpește cu 10% și apoi se ieftinește cu 10%. Cum va fi prețul?", VarA = "Peste 80 lei", VarB = "Tot 80 de lei", VarC = "Sub 80 de lei", RaspunsCorect = 3 },
new Question { Text = "Câți milimetri are un metru?", VarA = "0,001", VarB = "100", VarC = "1000", RaspunsCorect = 3 },
new Question { Text = "Dacă împart 10 la 3 și apoi rezultatul îl înmulțesc cu 3, o să rezulte:", VarA = "Mai mult de 10", VarB = "Exact 10", VarC = "Mai puțin de 10", RaspunsCorect = 3 },
new Question { Text = "Alerg la maraton și îl întrec pe cel de pe locul doi. Pe ce loc sunt?", VarA = "Primul loc", VarB = "Al doilea loc", VarC = "Al treilea loc", RaspunsCorect = 2 },
new Question { Text = "Suma tuturor unghiurilor dintr-un triunghi formează:", VarA = "360 de grade", VarB = "240 de grade", VarC = "180 de grade", RaspunsCorect = 3 },
new Question { Text = "Cu ce unealtă de pescuit se scoate peștele din apă când ajunge aproape de mal?", VarA = "Juvelnic", VarB = "Minciog", VarC = "Degorjor", RaspunsCorect = 2 },
new Question { Text = "Care este multiplul terabyteului?", VarA = "Zettabyte", VarB = "Yottabyte", VarC = "Petabyte", RaspunsCorect = 2 },
new Question { Text = "La ce dată se sărbătorește ziua națională a Franței?", VarA = "24 iulie", VarB = "14 iulie", VarC = "24 august", RaspunsCorect = 2 },
new Question { Text = "Parbrizul din spate al mașinii se numește:", VarA = "Lunetă", VarB = "Haion", VarC = "Eleron", RaspunsCorect = 1 },
new Question { Text = "Cum îl chema pe actorul din Vacanța mare care a murit într-un accident?", VarA = "Dan Sava", VarB = "Nugur Mihăiescu", VarC = "Ioan Gyuri Pascu", RaspunsCorect = 1 }
//176




            };
        }
    }
}
