using System.Collections.Generic;
using LearnGame26.Pages;

namespace LearnGame26.Pages
{
    public static class QuestionList2
    {
        public static List<Question> GetQuestions()
        {
            return new List<Question>
            {

new Question { Text = "Care este capitala statului Danemarca?", VarA = "Oslo", VarB = "Stockholm", VarC = "Copenhaga", RaspunsCorect = 3 },
new Question { Text = "După struț, care este cea mai mare pasăre de pe Pământ?", VarA = "Emu", VarB = "Tucanul", VarC = "Dropia", RaspunsCorect = 1 },
new Question { Text = "Câte continente există pe Pământ?", VarA = "5", VarB = "6", VarC = "7", RaspunsCorect = 3 },
new Question { Text = "Cine a pictat \"Carul cu boi\"?", VarA = "Ștefan Luchian", VarB = "Nicolae Tonitza", VarC = "Nicolae Grigorescu", RaspunsCorect = 3 },
new Question { Text = "Ce planetă este cunoscută ca Planeta Roșie?", VarA = "Venus", VarB = "Marte", VarC = "Jupiter", RaspunsCorect = 2 },
new Question { Text = "Care este înălțimea maximă din munții Carpați?", VarA = "2544", VarB = "2540", VarC = "2655", RaspunsCorect = 3 },
new Question { Text = "Cine se consideră că a inventat becul?", VarA = "Alexander Graham Bell", VarB = "Nikola Tesla", VarC = "Thomas Edison", RaspunsCorect = 3 },
new Question { Text = "Cum se numește cea mai mică componentă vizibilă de pe un ecran?", VarA = "megapixelul", VarB = "pixelul", VarC = "punctul", RaspunsCorect = 2 },
new Question { Text = "Ce țară este cea mai mare producătoare de cafea?", VarA = "Columbia", VarB = "Vietnam", VarC = "Brazilia", RaspunsCorect = 3 },
new Question { Text = "Care este cel mai mare ocean de pe Pământ?", VarA = "Oceanul Atlantic", VarB = "Oceanul Indian", VarC = "Oceanul Pacific", RaspunsCorect = 3 },

new Question { Text = "Care este singurul român care a câștigat Premiul Nobel pentru Literatură?", VarA = "Mihai Eminescu", VarB = "Mircea Eliade", VarC = "George Coșbuc", RaspunsCorect = 2 },
new Question { Text = "Cine este cunoscut ca „tată al telefonului mobil”?", VarA = "Alexander Graham Bell", VarB = "Martin Cooper", VarC = "Steve Jobs", RaspunsCorect = 2 },
new Question { Text = "Care este capitala Canadei?", VarA = "Toronto", VarB = "Vancouver", VarC = "Ottawa", RaspunsCorect = 3 },

new Question { Text = "Care este capitala Coreei de Nord?", VarA = "Seul", VarB = "Shanghai", VarC = "Phenian", RaspunsCorect = 3 },
new Question { Text = "Care este capitala statului Muntenegru?", VarA = "Pristina", VarB = "Podgorica", VarC = "Yerevan", RaspunsCorect = 2 },
new Question { Text = "Cine a descoperit pentru prima dată penicilina?", VarA = "Alexander Fleming", VarB = "Victor Babeș", VarC = "Charles Darwin", RaspunsCorect = 1 },
new Question { Text = "Care este capitala Irlandei?", VarA = "Dublin", VarB = "Helsinki", VarC = "Londra", RaspunsCorect = 1 },
new Question { Text = "Cine a inventat dinamita?", VarA = "Alfred Nobel", VarB = "Stephen Hawking", VarC = "Isaac Newton", RaspunsCorect = 1 },
new Question { Text = "Cine a fost fondatorul revistei Dacia Literară?", VarA = "Titu Maiorescu", VarB = "Mihai Eminescu", VarC = "Mihail Kogălniceanu", RaspunsCorect = 3 },
new Question { Text = "Mișcarea Pământului în jurul Soarelui poartă numele de:", VarA = "rotatie", VarB = "revoluție", VarC = "atracție", RaspunsCorect = 2 },
new Question { Text = "Care este capitala statului Georgia?", VarA = "Yerevan", VarB = "Tbilisi", VarC = "Minsk", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai înalt vârf montan din lume?", VarA = "Everest", VarB = "Aconcagua", VarC = "Olimp", RaspunsCorect = 1 },
new Question { Text = "Care este singurul lac de origine vulcanică din România?", VarA = "Sf. Ana", VarB = "Balea", VarC = "Bucura", RaspunsCorect = 1 },
new Question { Text = "Ce strâmtoare leagă Marea Neagră de Marea Marmara?", VarA = "Gibraltar", VarB = "Bosfor", VarC = "Dardanele", RaspunsCorect = 2 },
new Question { Text = "Prin ce stat trece Dunărea înainte de a intra în România?", VarA = "Croația", VarB = "Ungaria", VarC = "Serbia", RaspunsCorect = 3 },
new Question { Text = "Ce speranță de viață are în medie un cal?", VarA = "aproximativ 10-15 ani", VarB = "aproximativ 25-30 ani", VarC = "aproximativ 45-50 ani", RaspunsCorect = 2 },
new Question { Text = "Cât înseamnă 5% din 150?", VarA = "7,5", VarB = "15", VarC = "30", RaspunsCorect = 1 },
new Question { Text = "Cum se numește moneda oficială a Bulgariei?", VarA = "Leva", VarB = "Yen", VarC = "Forinți", RaspunsCorect = 1 },
new Question { Text = "Care este moneda oficială a Rusiei?", VarA = "Drahma", VarB = "Lira rusească", VarC = "Rubla", RaspunsCorect = 3 },
new Question { Text = "Care este reședința de județ pentru Dâmbovița?", VarA = "București", VarB = "Târgoviște", VarC = "Pitești", RaspunsCorect = 2 },
new Question { Text = "Care este reședința județului Caraș-Severin?", VarA = "Deva", VarB = "Caraș-Severin", VarC = "Reșița", RaspunsCorect = 3 },
new Question { Text = "Care este reședința județului Bihor?", VarA = "Deva", VarB = "Oradea", VarC = "Bihor", RaspunsCorect = 2 },
new Question { Text = "Cât fac 2+2*2?", VarA = "6", VarB = "8", VarC = "16", RaspunsCorect = 1 },
new Question { Text = "În triunghiul dreptunghic, laturile care formează unghiul drept poartă denumirea de:", VarA = "ipotenuze", VarB = "bisectoare", VarC = "catete", RaspunsCorect = 3 },
new Question { Text = "Cât fac radical din 12?", VarA = "2 radical din 3", VarB = "3", VarC = "4 radical din 3", RaspunsCorect = 1 },
new Question { Text = "Câte laturi are un cub?", VarA = "6", VarB = "4", VarC = "8", RaspunsCorect = 1 },
new Question { Text = "Care este cea de-a treia culoare din curcubeu?", VarA = "oranj", VarB = "roșu", VarC = "galben", RaspunsCorect = 3 },
new Question { Text = "Ce personalitate română se află pe bancnota de 500 lei?", VarA = "Ion Luca Caragiale", VarB = "Mihai Eminescu", VarC = "Lucian Blaga", RaspunsCorect = 2 },
new Question { Text = "Ce personalitate din România se află pe bancnota de 5 lei?", VarA = "George Enescu", VarB = "Ciprian Porumbescu", VarC = "Aurel Vlaicu", RaspunsCorect = 1 },

new Question { Text = "Care este capitala Australiei?", VarA = "Sydney", VarB = "Melbourne", VarC = "Canberra", RaspunsCorect = 3 },
new Question { Text = "Care planetă este cea mai apropiată de Soare?", VarA = "Jupiter", VarB = "Venus", VarC = "Mercur", RaspunsCorect = 3 },
new Question { Text = "Ce element chimic are simbolul Na?", VarA = "Nitrogen", VarB = "Sodiu", VarC = "Osmiu", RaspunsCorect = 2 },
new Question { Text = "Cine a inventat stiloul?", VarA = "Thomas Edison", VarB = "Nicolae Iorga", VarC = "Petrache Poienaru", RaspunsCorect = 3 },
new Question { Text = "Ce țară a găzduit Jocurile Olimpice de vară din 2016?", VarA = "China", VarB = "Brazilia", VarC = "Grecia", RaspunsCorect = 2 },
new Question { Text = "Cum îl cheamă pe singurul român care a ajuns în spațiu?", VarA = "Dumitru Prunariu", VarB = "Grigore Moisil", VarC = "Ivan Patzaichin", RaspunsCorect = 1 },
new Question { Text = "Care este cea mai mare planetă din sistemul solar?", VarA = "Saturn", VarB = "Jupiter", VarC = "Uranus", RaspunsCorect = 2 },
new Question { Text = "Care este cel mai lung fluviu din Europa?", VarA = "Dunărea", VarB = "Volga", VarC = "Fluviul Ural", RaspunsCorect = 2 },
new Question { Text = "Cine a fondat compania Microsoft?", VarA = "Steve Jobs", VarB = "Bill Gates", VarC = "Mark Zuckerberg", RaspunsCorect = 2 },
new Question { Text = "Ce sport se joacă la Wimbledon?", VarA = "Fotbal", VarB = "Tenis", VarC = "Golf", RaspunsCorect = 2 },
new Question { Text = "Ce animal este simbolul național al Australiei?", VarA = "Koala", VarB = "Cangur", VarC = "Emu", RaspunsCorect = 3 },
new Question { Text = "Cine a descoperit teoria relativității?", VarA = "Isaac Newton", VarB = "Albert Einstein", VarC = "Niels Bohr", RaspunsCorect = 2 },
new Question { Text = "Ce țară este renumită pentru vinul de Porto?", VarA = "Franța", VarB = "Spania", VarC = "Portugalia", RaspunsCorect = 3 },
new Question { Text = "Cine i-a urmat lui Steve Jobs la conducerea Apple?", VarA = "James Cook", VarB = "Jeff Bezos", VarC = "Sundar Pichai", RaspunsCorect = 3 },
new Question { Text = "Ce oraș este cunoscut ca \"Big Apple\"?", VarA = "Los Angeles", VarB = "Chicago", VarC = "New York", RaspunsCorect = 3 },
new Question { Text = "Ce monedă este folosită în Japonia?", VarA = "Yuan", VarB = "Yen", VarC = "Won", RaspunsCorect = 2 },
new Question { Text = "Cine a pictat \"Cina cea de taină\"?", VarA = "Raphael", VarB = "Michelangelo", VarC = "Leonardo da Vinci", RaspunsCorect = 3 },
new Question { Text = "Cine este cunoscut ca fiind \"Pele alb\"?", VarA = "Gerd Müller", VarB = "Zico", VarC = "Paulo Silas", RaspunsCorect = 1 },
new Question { Text = "Cine a fost antrenorul echipei FC Barcelona în sezonul 2008-2009?", VarA = "Luis Enrique", VarB = "Johan Cruyff", VarC = "Pep Guardiola", RaspunsCorect = 3 },
new Question { Text = "Cine este golgheterul all-time al echipei Real Madrid?", VarA = "Raúl", VarB = "Cristiano Ronaldo", VarC = "Alfredo Di Stéfano", RaspunsCorect = 2 },
new Question { Text = "Cine a marcat cele mai multe goluri în istoria Cupei Mondiale FIFA?", VarA = "Miroslav Klose", VarB = "Ronaldo", VarC = "Pele", RaspunsCorect = 1 },
new Question { Text = "Care este stadionul echipei Liverpool?", VarA = "Old Trafford", VarB = "Anfield", VarC = "Wembley", RaspunsCorect = 2 },
new Question { Text = "În ce an a câștigat Gheorghe Hagi premiul \"Fotbalistul Anului\" în România?", VarA = "1995", VarB = "1996", VarC = "1997", RaspunsCorect = 2 },
new Question { Text = "Care este echipa la care Gheorghe Hagi a jucat înainte de a se transfera la Galatasaray?", VarA = "Real Madrid", VarB = "Barcelona", VarC = "Bayern München", RaspunsCorect = 1 },
new Question { Text = "Care este numele echipei de fotbal pe care Gheorghe Hagi a antrenat-o între 2004 și 2005?", VarA = "Steaua București", VarB = "Galatasaray", VarC = "Kocaelispor", RaspunsCorect = 1 },
new Question { Text = "Care este numele fiului lui Gheorghe Hagi care este și el fotbalist?", VarA = "Ion Hagi", VarB = "Radu Hagi", VarC = "Ianis Hagi", RaspunsCorect = 3 },
new Question { Text = "Cine a fost adversarul României în meciul memorabil din sferturile de finală ale Campionatului Mondial 1994, în care Gheorghe Hagi a fost un jucător cheie?", VarA = "Germania", VarB = "Suedia", VarC = "Brazilia", RaspunsCorect = 2 },

new Question { Text = "În ce an a căzut Zidul Berlinului?", VarA = "1989", VarB = "1991", VarC = "1988", RaspunsCorect = 1 },
new Question { Text = "Între ce ani a domnit Carol al II-lea al României?", VarA = "1914-1927", VarB = "1927-1940", VarC = "1930-1940", RaspunsCorect = 3 },
new Question { Text = "Care a fost capitala Imperiului Bizantin?", VarA = "Roma", VarB = "Atena", VarC = "Constantinopol", RaspunsCorect = 3 },
new Question { Text = "Din ce an a venit la conducerea țării Nicolae Ceaușescu?", VarA = "1971", VarB = "1965", VarC = "1975", RaspunsCorect = 2 },
new Question { Text = "Unul dintre membrii PNȚ (partidul național țărănesc) este:", VarA = "Iuliu Maniu", VarB = "Ion I. C. Brătianu", VarC = "Gheorghe Tătărescu", RaspunsCorect = 1 },
new Question { Text = "Cum se numește ultimul președinte al Americii care a fost asasinat?", VarA = "Abraham Lincoln", VarB = "William McKinley", VarC = "John F. Kennedy", RaspunsCorect = 3 },
new Question { Text = "Ce popor antic a construit Machu Picchu?", VarA = "Aztecii", VarB = "Mayașii", VarC = "Incașii", RaspunsCorect = 3 },
new Question { Text = "Cine a fost conducătorul Uniunii Sovietice în timpul celui de-Al Doilea Război Mondial?", VarA = "Vladimir Lenin", VarB = "Iosif Stalin", VarC = "Leonid Brejnev", RaspunsCorect = 2 },
new Question { Text = "În ce an s-a desființat oficial URSS?", VarA = "1989", VarB = "1990", VarC = "1991", RaspunsCorect = 3 },
new Question { Text = "Care este numele actual al fostului oraș Constantinopol?", VarA = "Istanbul", VarB = "Bagdad", VarC = "Teheran", RaspunsCorect = 1 },
new Question { Text = "Cine a fost primul faraon al Egiptului unificat?", VarA = "Tutankhamon", VarB = "Narmer", VarC = "Ramses II", RaspunsCorect = 2 },
new Question { Text = "Cine a condus revoluția din Țara Românească în anul 1821?", VarA = "Tudor Vladimirescu", VarB = "Ion Heliade Rădulescu", VarC = "Nicolae Bălcescu", RaspunsCorect = 1 },
new Question { Text = "În ce an a avut loc răscoala lui Horea, Cloșca și Crișan?", VarA = "1820", VarB = "1784", VarC = "1848", RaspunsCorect = 2 },
new Question { Text = "În ce an a fost adoptată Reforma agrară din timpul lui Ferdinand I?", VarA = "1924", VarB = "1923", VarC = "1921", RaspunsCorect = 3 },
new Question { Text = "Care a fost rezultatul Războiului de 100 de ani?", VarA = "Victoria Franței", VarB = "Victoria Angliei", VarC = "Pacea de pe Marna", RaspunsCorect = 1 },
new Question { Text = "Cine a fost liderul revoluționar cubanez care a preluat puterea în 1959?", VarA = "Che Guevara", VarB = "Fidel Castro", VarC = "Raul Guevara", RaspunsCorect = 2 },
new Question { Text = "Care a fost numele planului economic american pentru reconstrucția Europei după al Doilea Război Mondial?", VarA = "Planul Marshall", VarB = "Operațiunea Barbarossa", VarC = "Planul Dawes", RaspunsCorect = 1 },
new Question { Text = "În ce an a început Războiul Rece?", VarA = "1945", VarB = "1947", VarC = "1950", RaspunsCorect = 2 },
new Question { Text = "Cine a fost primul ministru britanic în timpul celui de-Al Doilea Război Mondial?", VarA = "Winston Churchill", VarB = "Neville Chamberlain", VarC = "Clement Attlee", RaspunsCorect = 1 },
new Question { Text = "Ce eveniment a declanșat Primul Război Mondial?", VarA = "Invadarea Poloniei", VarB = "Asasinarea Arhiducelui Franz Ferdinand", VarC = "Atacul de la Pearl Harbor", RaspunsCorect = 2 },
//86

new Question { Text = "What is the superlative form of the adjective good?", VarA = "better", VarB = "the most", VarC = "the best", RaspunsCorect = 3 },
new Question { Text = "What is the past tense of 'say'?", VarA = "to say", VarB = "said", VarC = "sed", RaspunsCorect = 2 },
new Question { Text = "Which of the following is a synonym for 'overweight'?", VarA = "fat", VarB = "joyful", VarC = "tired", RaspunsCorect = 1 },
new Question { Text = "What is the opposite of 'north'?", VarA = "sud", VarB = "south", VarC = "west", RaspunsCorect = 2 },
new Question { Text = "Choose the correct sentence: 'She ______ pizza yesterday.'", VarA = "mades", VarB = "makes", VarC = "made", RaspunsCorect = 3 },
new Question { Text = "What is the plural form of 'fish'?", VarA = "fish", VarB = "fisheses", VarC = "feesh", RaspunsCorect = 1 },
new Question { Text = "Which word is a noun?", VarA = "run", VarB = "beautiful", VarC = "dog", RaspunsCorect = 3 },
new Question { Text = "What is the comparative form of 'ill'?", VarA = "the most ill", VarB = "more ill", VarC = "worse", RaspunsCorect = 3 },
new Question { Text = "Complete the sentence: 'I have ______ apples than you.'", VarA = "few", VarB = "fewer", VarC = "less", RaspunsCorect = 2 },
new Question { Text = "Which of the following is a preposition?", VarA = "under", VarB = "quickly", VarC = "run", RaspunsCorect = 1 },
new Question { Text = "What is the antonym of 'ancient'?", VarA = "old", VarB = "new", VarC = "young", RaspunsCorect = 2 },
new Question { Text = "What is the third person singular form of 'to be' in the present tense?", VarA = "am", VarB = "is", VarC = "are", RaspunsCorect = 2 },
new Question { Text = "What is the synonym of may?", VarA = "might", VarB = "must not", VarC = "have not", RaspunsCorect = 1 },
new Question { Text = "Choose the correct word: 'He is taller ______ her.'", VarA = "then", VarB = "than", VarC = "that", RaspunsCorect = 2 },
new Question { Text = "What is the past participle of 'eat'?", VarA = "ate", VarB = "eaten", VarC = "eats", RaspunsCorect = 2 },
new Question { Text = "Complete the sentence: 'They are ______ their homework.'", VarA = "do", VarB = "doing", VarC = "did", RaspunsCorect = 2 },
new Question { Text = "What is the adjective form of 'beauty'?", VarA = "beautiful", VarB = "beautify", VarC = "beautiness", RaspunsCorect = 1 },
new Question { Text = "Choose the correct answer: '______ are you going?'", VarA = "Where", VarB = "Were", VarC = "Wear", RaspunsCorect = 1 },
new Question { Text = "What is the superlative form of 'happy'?", VarA = "happier", VarB = "happiest", VarC = "most happy", RaspunsCorect = 2 },
new Question { Text = "Which of the following is a conjunction?", VarA = "and", VarB = "quickly", VarC = "the", RaspunsCorect = 1 },

new Question { Text = "În finalul romanului Jane Eyre, ce se întâmplă cu Edward Rochester?", VarA = "este ucis", VarB = "se sinucide", VarC = "orbește", RaspunsCorect = 3 },
new Question { Text = "Una dintre primele scrieri românești din 1521 este cunoscută ca:", VarA = "Scrisoarea lui Neacșu de la Câmpulung", VarB = "Letopisețul Moldovei", VarC = "Cronica notarului anonim", RaspunsCorect = 1 },
new Question { Text = "Care este autorul romanului 'Patul lui Procrust'?", VarA = "Camil Petrescu", VarB = "George Călinescu", VarC = "Mihai Drumeș", RaspunsCorect = 1 },
new Question { Text = "Cine a scris romanul 'Ciocoii vechi și noi'?", VarA = "Mihail Sadoveanu", VarB = "Tudorel Filimon", VarC = "Nicolae Filimon", RaspunsCorect = 3 },
new Question { Text = "Din câte volume este alcătuit romanul Cireșarii scris de Constantin Chiriță?", VarA = "5", VarB = "2", VarC = "4", RaspunsCorect = 1 },
new Question { Text = "Cine a scris romanul 'Toate pânzele sus'?", VarA = "Radu Tudoran", VarB = "Mihai Drumeș", VarC = "Costache Negruzzi", RaspunsCorect = 1 },
new Question { Text = "Cine este autorul povestirii 'Călătoriile lui Gulliver'?", VarA = "Jonathan Swift", VarB = "Daniel Defoe", VarC = "Mark Twain", RaspunsCorect = 1 },
new Question { Text = "Care este poetul care a realizat opera 'Leoaică tânără, iubirea'?", VarA = "George Bacovia", VarB = "Mihai Eminescu", VarC = "Nichita Stănescu", RaspunsCorect = 3 },
new Question { Text = "În structura unei opere, ce etapă urmează de obicei după punctul culminant?", VarA = "intriga", VarB = "expozitiunea", VarC = "deznodământul", RaspunsCorect = 3 },
new Question { Text = "Care este autorul romanului 'Marele Gatsby'?", VarA = "Ernest Hemingway", VarB = "F. Scott Fitzgerald", VarC = "J.D. Salinger", RaspunsCorect = 2 },
new Question { Text = "Cine a scris romanul 'Micul prinț'?", VarA = "Jules Verne", VarB = "Antoine de Saint-Exupéry", VarC = "Albert Camus", RaspunsCorect = 2 },
new Question { Text = "Ce specie a genului epic este opera 'Amintiri din copilărie' scrisă de Ion Creangă?", VarA = "roman", VarB = "basm", VarC = "poveste", RaspunsCorect = 2 },
new Question { Text = "Cine a scris tragedia antică 'Oedip rege'?", VarA = "Euripides", VarB = "Sophocles", VarC = "Aristophanes", RaspunsCorect = 2 },
new Question { Text = "Ce autor este cunoscut pentru atracția sa față de tei?", VarA = "Mihai Eminescu", VarB = "Lucian Blaga", VarC = "Vasile Alecsandri", RaspunsCorect = 1 },
new Question { Text = "Cum se numește alăturarea de două cuvinte sau expresii cu sensuri opuse?", VarA = "omonim", VarB = "antonim", VarC = "oximoron", RaspunsCorect = 3 },
new Question { Text = "Care este autorul romanului 'În căutarea timpului pierdut'?", VarA = "Marcel Proust", VarB = "Victor Hugo", VarC = "Stendhal", RaspunsCorect = 1 },
new Question { Text = "Cine a scris romanul 'Frații Karamazov'?", VarA = "Franz Kafka", VarB = "Fiodor Dostoievski", VarC = "Gabriel Garcia Marquez", RaspunsCorect = 2 },
new Question { Text = "Care este autorul romanului 'Alice în Țara Minunilor'?", VarA = "Lewis Carroll", VarB = "J.M. Barrie", VarC = "Roald Dahl", RaspunsCorect = 1 },
new Question { Text = "În ce an a fost publicat romanul 'Ion' scris de Liviu Rebreanu?", VarA = "1930", VarB = "1927", VarC = "1920", RaspunsCorect = 3 },

new Question { Text = "În ce an a fost semnat Tratatul de la Versailles?", VarA = "1919", VarB = "1920", VarC = "1918", RaspunsCorect = 1 },
new Question { Text = "Cine a fost conducătorul Imperiului Otoman în timpul Bătăliei de la Lepanto?", VarA = "Suleiman Magnificul", VarB = "Selim II", VarC = "Ahmed I", RaspunsCorect = 2 },
new Question { Text = "Cine a fost liderul Revoluției Ruse din 1917?", VarA = "Vladimir Lenin", VarB = "Leon Troțki", VarC = "Josef Stalin", RaspunsCorect = 1 },
new Question { Text = "Care a fost primul împărat al Chinei?", VarA = "Qin Shi Huang", VarB = "Liu Bei", VarC = "Kublai Khan", RaspunsCorect = 1 },
new Question { Text = "Cine a fost primul rege al Franței?", VarA = "Hugh Capet", VarB = "Clovis I", VarC = "Louis XIV", RaspunsCorect = 2 },
new Question { Text = "Care a fost numele oficial al Germaniei în timpul celui de-al Doilea Război Mondial?", VarA = "Republica Weimar", VarB = "Imperiul German", VarC = "Germania Hitleristă", RaspunsCorect = 2 },
new Question { Text = "Cine a fost principalul adversar al Romei în Războaiele Punice?", VarA = "Cartagina", VarB = "Egipt", VarC = "Galia", RaspunsCorect = 1 },
new Question { Text = "Care a fost prima civilizație care a utilizat scrisul?", VarA = "Mesopotamia", VarB = "Egipt", VarC = "Indus", RaspunsCorect = 1 },
new Question { Text = "Cine a fost liderul mișcării pentru drepturile civile din Statele Unite în anii 1960?", VarA = "Martin Luther King Jr.", VarB = "Malcolm X", VarC = "Rosa Parks", RaspunsCorect = 1 },
new Question { Text = "În ce an a fost înființată Uniunea Europeană?", VarA = "1993", VarB = "1989", VarC = "2001", RaspunsCorect = 1 },
new Question { Text = "Cine a fost liderul Războiului de Independență al Indiei?", VarA = "Mahatma Gandhi", VarB = "Jawaharlal Nehru", VarC = "Subhas Chandra Bose", RaspunsCorect = 1 },
new Question { Text = "Cine a condus Imperiul Mongol în perioada de apogeu?", VarA = "Genghis Khan", VarB = "Kublai Khan", VarC = "Ogedei Khan", RaspunsCorect = 1 },
new Question { Text = "Cine a fost primul rege al României?", VarA = "Carol I", VarB = "Ferdinand I", VarC = "Mihai I", RaspunsCorect = 1 },
new Question { Text = "În ce an a avut loc Revoluția Industrială?", VarA = "1760", VarB = "1850", VarC = "1900", RaspunsCorect = 1 },
new Question { Text = "În ce an s-a scufundat Titanicul?", VarA = "1932", VarB = "1912", VarC = "1925", RaspunsCorect = 2 },
new Question { Text = "În ce an a fost construit Marele Zid Chinezesc?", VarA = "210 î.Hr.", VarB = "500 d.Hr.", VarC = "1000 d.Hr.", RaspunsCorect = 1 },
//141

new Question { Text = "Ce tehnologie este folosită pentru stocarea datelor pe discuri optice?", VarA = "CD-ROM", VarB = "HDD", VarC = "SSD", RaspunsCorect = 1 },
new Question { Text = "Pentru a selecta câte un cuvânt într-un editor text, utilizăm combinația de taste:", VarA = "shift+săgeată dreapta", VarB = "shift+săgeată jos", VarC = "shift+ctrl+săgeată dreapta", RaspunsCorect = 3 },
new Question { Text = "Ce este un microprocesor?", VarA = "Un dispozitiv de stocare", VarB = "Unitatea centrală de procesare a unui computer", VarC = "Un tip de memorie RAM", RaspunsCorect = 2 },
new Question { Text = "Ce este Java?", VarA = "Un limbaj de programare", VarB = "Un sistem de operare", VarC = "Un limbaj de marcare pentru paginile web", RaspunsCorect = 1 },
new Question { Text = "Cine a inventat primul calculator personal?", VarA = "Bill Gates", VarB = "Steve Jobs", VarC = "Alan Turing", RaspunsCorect = 2 },
new Question { Text = "Ce tehnologie este folosită pentru transmiterea semnalelor wireless?", VarA = "Bluetooth", VarB = "Ethernet", VarC = "USB", RaspunsCorect = 1 },
new Question { Text = "Care este semnul cu care trebuie să se încheie obligatoriu o linie de cod în C#?", VarA = "virgulă", VarB = "punct și virgulă", VarC = "cratimă", RaspunsCorect = 2 },
new Question { Text = "Ce înseamnă hardware?", VarA = "totalitatea programelor", VarB = "componentele fizice", VarC = "memoria calculatorului", RaspunsCorect = 2 },
new Question { Text = "Ce componentă a unui computer este responsabilă pentru afișarea imaginii?", VarA = "Placa de bază", VarB = "Procesorul", VarC = "Placa video", RaspunsCorect = 3 },
new Question { Text = "Care este cea mai populară bază de date relațională?", VarA = "MongoDB", VarB = "MySQL", VarC = "Redis", RaspunsCorect = 2 },
new Question { Text = "Ce este un IP static?", VarA = "O adresă IP care se schimbă periodic", VarB = "O adresă IP fixă atribuită unui dispozitiv", VarC = "O adresă IP care se schimbă la fiecare accesare", RaspunsCorect = 2 },
new Question { Text = "Dintre o cartelă micro-sim și una nano-sim, care este mai mică?", VarA = "nano-sim", VarB = "micro-sim", VarC = "mărimea este aceeași", RaspunsCorect = 1 },
new Question { Text = "Ce înseamnă acronimul \"HTTP\"?", VarA = "Hypertext Transfer Protocol", VarB = "Hyperlink Transfer Protocol", VarC = "High Text Transfer Protocol", RaspunsCorect = 1 },
new Question { Text = "Care este cea mai eficientă stabilizare în contextul camerelor foto de pe smartphone?", VarA = "digitală", VarB = "statică", VarC = "optică", RaspunsCorect = 3 },
new Question { Text = "Ce comandă utilizăm pentru navigarea între ferestrele deschise de pe PC?", VarA = "alt+tab", VarB = "ctrl+tab", VarC = "windows+tab", RaspunsCorect = 1 },
new Question { Text = "Ce este un \"data breach\"?", VarA = "Un atac cibernetic asupra hardware-ului", VarB = "Un incident în care datele personale sunt accesate neautorizat", VarC = "Un defect în software", RaspunsCorect = 2 },
new Question { Text = "Pentru a avea cea mai scăzută latență folosim:", VarA = "bluetooth", VarB = "wi-fi", VarC = "cablul fizic", RaspunsCorect = 3 },
new Question { Text = "Ce tehnologie folosită la ecranele TV produce mai multă lumină?", VarA = "oled", VarB = "poled", VarC = "miniled", RaspunsCorect = 3 },
//159

new Question { Text = "În timpul cărui președinte român mandatul pentru șeful statului a crescut la 5 ani?", VarA = "Claus Iohannis", VarB = "Emil Constantinescu", VarC = "Traian Băsescu", RaspunsCorect = 3 },
new Question { Text = "Cele două oase ce încep de la cot și se termină la încheietură se numesc:", VarA = "Cubitus și radius", VarB = "Ilion și ischion", VarC = "Tarsian și meta-tarsian", RaspunsCorect = 1 },
new Question { Text = "În ce an a intrat România în U.E.?", VarA = "2003", VarB = "2007", VarC = "1999", RaspunsCorect = 2 },
new Question { Text = "Câte laturi egale are un triunghi isoscel?", VarA = "Trei laturi", VarB = "Nicio latură", VarC = "Două laturi", RaspunsCorect = 3 },
new Question { Text = "Care este cea mai dură piatră prețioasă?", VarA = "Safirul", VarB = "Diamantul", VarC = "Rubinul", RaspunsCorect = 2 },
new Question { Text = "Prin care dintre următoarele metode rufele se usucă cel mai rapid:", VarA = "Cu ajutorul Soarelui", VarB = "Cu ajutorul vântului", VarC = "Cu ajutorul temperaturilor scăzute", RaspunsCorect = 2 },
new Question { Text = "Care este cea mai veche universitate din lume?", VarA = "Al-Karaouine", VarB = "Cambridge", VarC = "Sorbona", RaspunsCorect = 1 },
new Question { Text = "În ce stat se află cea mai veche universitate din lume?", VarA = "S.U.A.", VarB = "U.K.", VarC = "Maroc", RaspunsCorect = 3 },
new Question { Text = "De unde s-a stabilit că provine limba latină?", VarA = "Latium", VarB = "Sorbona", VarC = "Verona", RaspunsCorect = 1 },
new Question { Text = "Condimentul esențial în prepararea gulașului este:", VarA = "Chimenul", VarB = "Boiaua", VarC = "Oregano", RaspunsCorect = 2 },
new Question { Text = "Câte cântăriri se pot face minim pentru a afla care bilă dintr-un total de 9 este mai grea?", VarA = "6 cântăriri", VarB = "4 cântăriri", VarC = "3 cântăriri", RaspunsCorect = 3 },
new Question { Text = "A transvaza înseamnă:", VarA = "A muta lichidul dintr-un recipient în altul", VarB = "A muta florile dintr-o vază în alta", VarC = "A pune un obiect într-un vas", RaspunsCorect = 1 },
new Question { Text = "Cum se numește prima vertebră din coloana vertebrală umană?", VarA = "Atlas", VarB = "Axis", VarC = "Ischion", RaspunsCorect = 1 },
new Question { Text = "Ca un aluat să fie fraged folosim:", VarA = "Bicarbonat", VarB = "Praf de copt", VarC = "Drojdie", RaspunsCorect = 2 }
//173

            };
        }
    }
}
